services:
  - type: web
    name: x-reply-counter
    env: python
    buildCommand: |
      apt-get update && apt-get install -y wget unzip curl
      && wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      && apt install -y ./google-chrome-stable_current_amd64.deb
      && pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port 10000
