services:
  - type: web
    name: x-reply-counter
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port 10000 --server.enableCORS false
